runmode: debug
addr: :8080
name: go-options
url: http://127.0.0.1:8080
max_ping_count: 10
jwt_secret: xxxx
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/options.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_options
  addr: 127.0.0.1
  username: root
  password: root
docker_db:
  name: db_options
  addr: 127.0.0.1
  username: root
  password: root
